Repository prography/10th-3team-minari-BE, pull requests merged in 2025-07, with the labels that each got.

#105 [HOTFIX] user oauth login 수정
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
Labels: 🐞 BugFix

#89 [Feat(#80)] 이메일 전송 배치적용
  build.gradle
  src/main/java/com/prography/minari/batch/item/processor/MailContentCreateProcessor.java
  src/main/java/com/prography/minari/batch/item/reader/UserItemReader.java
  src/main/java/com/prography/minari/batch/item/writer/MailSendWriter.java
  src/main/java/com/prography/minari/batch/job/MailJobConfiguration.java
  src/main/java/com/prography/minari/batch/jobLauncher/MailSendLauncher.java
  src/main/java/com/prography/minari/batch/step/MailSendStep.java
  src/main/java/com/prography/minari/mail/dto/MailSubject.java
  src/main/java/com/prography/minari/mail/entity/MailAuthLog.java
  src/main/java/com/prography/minari/mail/service/MailClient.java
  src/main/java/com/prography/minari/mail/service/MailService.java
  src/main/java/com/prography/minari/mail/service/impl/GoogleMailClient.java
  src/main/java/com/prography/minari/mail/service/impl/MailTemplateCreater.java
  src/main/resources/application-live.yml
  src/main/resources/application-local.yml
  src/main/resources/templates/no-have-problem.html
  src/main/resources/templates/today-minari.html
Labels: ✨ Feature

#106 [FEAT(#85)] 로그아웃 및 토큰 재발급 관련 정책 및 기능 개발
  src/main/java/com/prography/minari/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/prography/minari/common/service/impl/RedisProcessor.java
  src/main/java/com/prography/minari/common/util/JwtUtil.java
  src/main/java/com/prography/minari/social/service/SocialService.java
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
  src/main/java/com/prography/minari/user/dto/UserLoginResDto.java
  src/main/java/com/prography/minari/user/service/UserService.java
Labels: ⚙ Setting, 📬 API, ✨ Feature, 🔨 Refactor

#93 [Feat(#90)] AWS S3 음성파일 적재 기능
  build.gradle
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/aws/impl/FileUploader.java
  src/main/java/com/prography/minari/aws/impl/S3Uploader.java
  src/main/java/com/prography/minari/common/config/AwsS3Config.java
  src/main/java/com/prography/minari/mail/service/MailService.java
Labels: 🥰 Accessibility

#115 [Feat(#104)] 결제DB설계 및 씨앗 지급, 조회 API 개발
  src/main/java/com/prography/minari/admin/controller/AdminController.java
  src/main/java/com/prography/minari/admin/controller/docs/AdminApiDocs.java
  src/main/java/com/prography/minari/admin/controller/dto/RewardForceV2Request.java
  src/main/java/com/prography/minari/admin/service/AdminRewardService.java
  src/main/java/com/prography/minari/payment/controller/CreditController.java
  src/main/java/com/prography/minari/payment/controller/docs/CreditApiDocs.java
  src/main/java/com/prography/minari/payment/entity/AccountPayment.java
  src/main/java/com/prography/minari/payment/entity/Credit.java
  src/main/java/com/prography/minari/payment/entity/CreditStatus.java
  src/main/java/com/prography/minari/payment/entity/CreditUsage.java
  src/main/java/com/prography/minari/payment/entity/PGPayment.java
  src/main/java/com/prography/minari/payment/entity/Payment.java
  src/main/java/com/prography/minari/payment/repository/CreditJpaRepository.java
  src/main/java/com/prography/minari/payment/repository/CreditUsageJpaRepository.java
  src/main/java/com/prography/minari/payment/repository/PaymentJpaRepository.java
  src/main/java/com/prography/minari/payment/service/CreditService.java
  src/main/java/com/prography/minari/payment/service/impl/CreditCounter.java
  src/main/java/com/prography/minari/payment/service/impl/CreditWriter.java
  src/main/java/com/prography/minari/payment/service/impl/PaymentWriter.java
  src/test/java/com/prography/minari/payment/service/impl/CreditCounterTest.java
Labels: 📬 API, ✨ Feature

#120 [FEAT(#116)] 인증 메일 템플릿 수정
  src/main/resources/templates/auth-mail.html
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#111 [FEAT(#108)] 계정 휴면 상태 해제 API
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/main/java/com/prography/minari/user/service/UserService.java
  src/main/java/com/prography/minari/user/service/impl/UserWriter.java
Labels: ✨ Feature

#122 [FEAT(#116)] 리허설 중복 적재 기능 개발
  src/main/java/com/prography/minari/answer/entity/Answer.java
  src/main/java/com/prography/minari/answer/repository/AnswerRepository.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/impl/AnswerReader.java
  src/main/java/com/prography/minari/user/service/UserService.java
  src/test/java/com/prography/minari/answer/service/impl/AnswerReaderTest.java
Labels: ✨ Feature, 🔨 Refactor

#147 [FEAT(#146)] 이메일 인증 요청 시, 이미 등록된 이메일인 경우 예외 처리
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/mail/service/MailService.java
  src/main/java/com/prography/minari/user/repository/UserRepository.java
  src/main/java/com/prography/minari/user/service/impl/UserReader.java
Labels: ✨ Feature, 🔨 Refactor

#136 [FEAT(#130)] ADMIN 필터 추가하기
  src/main/java/com/prography/minari/admin/controller/AdminController.java
  src/main/java/com/prography/minari/common/config/SecurityConfig.java
  src/main/java/com/prography/minari/common/execption/CustomAuthenticationException.java
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/prography/minari/common/handler/CustomAccessDeniedHandler.java
  src/main/java/com/prography/minari/common/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/prography/minari/common/util/JwtUtil.java
  src/main/java/com/prography/minari/social/service/SocialService.java
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/main/java/com/prography/minari/user/enums/UserRole.java
  src/main/java/com/prography/minari/user/service/UserService.java
  src/main/java/com/prography/minari/user/service/impl/UserReader.java
Labels: ✨ Feature, 🔨 Refactor
