Repository prography/10th-3team-minari-BE, pull requests merged in 2025-06, with the labels that each got.

#39 [Feat(#3)] Stt변환 로직에 1분으로 파일 자르는 로직 추가
  .gitignore
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/dto/SttResponseDto.java
  src/main/java/com/prography/minari/answer/service/dto/response/InterviewContentResponse.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttProcessor.java
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/test/java/com/prography/minari/answer/service/impl/SttApiClientTest.java
Labels: 📬 API, ✨ Feature

#40 [Feat(#18)] 오늘의 미나리 조회기능
  build.gradle
  src/main/java/com/prography/minari/common/entity/Domain.java
  src/main/java/com/prography/minari/question/DailyUserQuestionResDto.java
  src/main/java/com/prography/minari/question/controller/QuestionController.java
  src/main/java/com/prography/minari/question/entity/Level.java
  src/main/java/com/prography/minari/question/entity/Question.java
  src/main/java/com/prography/minari/question/repository/QuestionRepository.java
  src/main/java/com/prography/minari/question/service/QuestionService.java
  src/main/java/com/prography/minari/question/service/impl/QuestionReader.java
  src/main/java/com/prography/minari/user/entity/PreferDomain.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/test/java/com/prography/minari/question/entity/QuestionTest.java
  src/test/java/com/prography/minari/question/service/QuestionServiceTest.java
  src/test/java/com/prography/minari/question/service/impl/QuestionReaderTest.java
  src/test/resources/application-default.yml
Labels: 📬 API, ✨ Feature

#43 [Refactor(#23)] appspec.yml file섹션 삭제
  appspec.yml
Labels: 🌏 Deploy

#55 [Feat(#3)] 문제에 대한 답변 및 정답 조회기능
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/controller/docs/AnswerApiDocs.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/common/handler/GlobalExceptionHandler.java
  src/main/java/com/prography/minari/common/response/ApiResponse.java
  src/main/java/com/prography/minari/common/response/CommonResponse.java
  src/main/java/com/prography/minari/question/controller/QuestionController.java
  src/main/java/com/prography/minari/question/controller/docs/QuestionApiDocs.java
  src/main/java/com/prography/minari/question/service/QuestionService.java
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/resources/application-local.yml
  src/test/java/com/prography/minari/answer/service/AnswerServiceTest.java
  src/test/resources/application-default.yml
Labels: 📬 API, ✨ Feature

#60 [Refactor(#59)] STT변환시 API지원 포맷으로 형변환
  build.gradle
  scripts/deploy.sh
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/impl/AudioFileFormatConverter.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttProcessor.java
Labels: ✨ Feature, 🔨 Refactor

#58 [FEAT(#42)] 유저 회원가입 로직 테스트 코드 작성
  src/main/java/com/prography/minari/social/dto/social/UserInfoDto.java
  src/main/java/com/prography/minari/user/dto/UserJoinReqDto.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/main/java/com/prography/minari/user/service/UserService.java
  src/main/java/com/prography/minari/user/service/impl/UserWriter.java
  src/test/java/com/prography/minari/social/service/SocialServiceTest.java
  src/test/java/com/prography/minari/user/service/UserServiceTest.java
Labels: ✅ Test

#61 [Fix(#59)] ffmpeg도커이미지 경로 수정
  scripts/deploy.sh
  src/main/java/com/prography/minari/answer/service/impl/AudioFileFormatConverter.java
Labels: 🐞 BugFix, 🌏 Deploy

#64 [Fix(#59)] 스프링 프로젝트 내부가 아닌 호스트 절대경로로 수정
  src/main/java/com/prography/minari/answer/service/impl/AudioFileFormatConverter.java
Labels: 🐞 BugFix

#70 [Feat(#4)] JpaAuditing 설정추가
  src/main/java/com/prography/minari/common/config/AuditingConfig.java
Labels: ⚙ Setting

#75 [FEAT(#74)] 응답 형식 통일
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
Labels: 🔨 Refactor

#77 [Perf(#69)] api호출시 non-blocking방식으로 개선
  src/main/java/com/prography/minari/answer/entity/Answer.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttProcessor.java
Labels: 🔨 Refactor

#88 [Chore(#87)] ssh tunneling으로 실DB 세팅
  .gitignore
  build.gradle
  src/main/java/com/prography/minari/common/config/SshDataSourceConfig.java
  src/main/java/com/prography/minari/common/config/SshTunnelingInitializer.java
Labels: ⚙ Setting

#99 [FEAT(#81)] 문제가 없을 시, 예외처리
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/common/handler/GlobalExceptionHandler.java
  src/main/java/com/prography/minari/question/service/impl/QuestionReader.java
Labels: 🐞 BugFix, 🔨 Refactor

#101 [FEAT(#100)]유저 정보 조회시, seed 필드 추가
  src/main/java/com/prography/minari/payment/entity/Seed.java
  src/main/java/com/prography/minari/user/controller/docs/UserApiDocs.java
  src/main/java/com/prography/minari/user/dto/UserFindResDto.java
  src/main/java/com/prography/minari/user/service/UserService.java
Labels: 🔨 Refactor

#102 [HOTFIX] user 정보 조회 api, common response 적용
  src/main/java/com/prography/minari/user/controller/UserController.java
Labels: 🐞 BugFix
