Repository prography/10th-3team-minari-BE, pull requests merged in 2025-05, with the labels that each got.

#2 [FEAT] 서버 테스트를 위한 헬스체크 API
  .gitignore
  Dockerfile
  src/main/java/com/prography/minari/common/controller/CommonController.java
Labels: ⚙ Setting, 📬 API, ✨ Feature

#5 [FEAT] 기본 엔티티 구성
  .gitignore
  build.gradle
  src/main/java/com/prography/minari/answer/Answer.java
  src/main/java/com/prography/minari/common/entity/BaseTimeEntity.java
  src/main/java/com/prography/minari/question/Question.java
  src/main/java/com/prography/minari/user/User.java
Labels: ✨ Feature

#8 [Feat(#3)] 면접 프로세스 API
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/entity/Answer.java
  src/main/java/com/prography/minari/answer/repository/AnswerRepository.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/dto/response/InterviewContentResponse.java
  src/main/java/com/prography/minari/answer/service/impl/AnswerWriter.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttApiClient.java
  src/main/java/com/prography/minari/answer/service/impl/SttProcessor.java
  src/main/java/com/prography/minari/common/aop/ImplService.java
  src/main/java/com/prography/minari/question/controller/QuestionController.java
  src/main/java/com/prography/minari/question/entity/Question.java
  src/main/java/com/prography/minari/question/repository/QuestionRepository.java
  src/main/java/com/prography/minari/question/service/QuestionService.java
  src/main/java/com/prography/minari/question/service/impl/QuestionReader.java
  src/main/java/com/prography/minari/social/service/KakaoSocialServiceImpl.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/main/java/com/prography/minari/user/repository/UserRepository.java
  src/main/java/com/prography/minari/user/service/UserServiceImpl.java
  src/main/java/com/prography/minari/user/service/impl/UserReader.java
  src/test/java/com/prography/minari/answer/service/AnswerServiceTest.java
  src/test/java/com/prography/minari/answer/service/impl/AnswerWriterTest.java
  src/test/java/com/prography/minari/answer/service/impl/SttApiClientTest.java
  src/test/java/com/prography/minari/question/service/impl/QuestionReaderTest.java
Labels: 📬 API, ✨ Feature

#10 [FEAT] postgresql 라이브러리 추가
  build.gradle
Labels: ⚙ Setting

#15 [FEAT(#14)] CORS Configuration 생성
  src/main/java/com/prography/minari/common/config/CorsConfig.java
Labels: ⚙ Setting, 🥰 Accessibility, 💻 CrossBrowsing

#16 [Feat(#3)] STT변환 상태체크
  build.gradle
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/entity/Answer.java
  src/main/java/com/prography/minari/answer/repository/AnswerRepository.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/dto/SttStatus.java
  src/main/java/com/prography/minari/answer/service/dto/UserAnswerStatusResponse.java
  src/main/java/com/prography/minari/answer/service/impl/AnswerReader.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/common/execption/ApiException.java
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/common/handler/GlobalExceptionHandler.java
  src/main/java/com/prography/minari/common/response/ApiResponse.java
  src/main/java/com/prography/minari/question/service/QuestionService.java
  src/main/java/com/prography/minari/question/service/impl/QuestionReader.java
  src/main/java/com/prography/minari/user/entity/User.java
  src/test/java/com/prography/minari/answer/service/AnswerServiceTest.java
  src/test/java/com/prography/minari/question/service/impl/QuestionReaderTest.java
Labels: 📬 API, ✨ Feature

#17 [Refactor(#3)] 면접음성 STT변환 및 저장기능
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/dto/SttConvertResponse.java
  src/main/java/com/prography/minari/answer/service/dto/response/NaverSttApiResponse.java
  src/main/java/com/prography/minari/answer/service/dto/response/UserAnswerStatusResponse.java
  src/main/java/com/prography/minari/answer/service/impl/NaverApiClient.java
  src/main/java/com/prography/minari/user/service/impl/UserReader.java
  src/test/java/com/prography/minari/answer/service/AnswerServiceTest.java
  src/test/java/com/prography/minari/answer/service/impl/SttApiClientTest.java
Labels: 📬 API, 🔨 Refactor

#21 [Feat(#3)] 답변한 질문정보 조회
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/repository/AnswerRepository.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/answer/service/impl/AnswerReader.java
Labels: 📬 API, ✨ Feature

#28 [Deploy(#23)] CICD 설정 추가
  .gitignore
  Dockerfile
  appspec.yml
  buildspec.yml
  scripts/deploy.sh
  src/main/resources/application-live.yml
  src/main/resources/application-local.yml
Labels: 🌏 Deploy

#25 [FEAT(#20)] JWT 발급 기능
  build.gradle
  src/main/java/com/prography/minari/common/execption/ApiException.java
  src/main/java/com/prography/minari/common/handler/GlobalExceptionHandler.java
  src/main/java/com/prography/minari/common/response/ApiResponse.java
  src/main/java/com/prography/minari/common/util/JwtUtil.java
  src/main/java/com/prography/minari/social/service/KakaoSocialServiceImpl.java
  src/main/java/com/prography/minari/user/dto/UserLoginResDto.java
Labels: ✨ Feature

#31 <hotfix> gitignre 파일, /src/main/resources/ 추가
  .gitignore
Labels: ⚙ Setting

#33 [Deploy(#23)] application-live.yml 파일 개행 수정
  src/main/resources/application-live.yml
  src/main/resources/application-local.yml
Labels: 🌏 Deploy

#35 [Docs(#24)] 스웨거 설정 추가
  build.gradle
  src/main/java/com/prography/minari/answer/controller/AnswerController.java
  src/main/java/com/prography/minari/answer/controller/docs/AnswerApiDocs.java
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/common/execption/ApiException.java
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/common/util/JwtUtil.java
  src/main/java/com/prography/minari/question/controller/QuestionController.java
  src/main/java/com/prography/minari/question/controller/docs/QuestionApiDocs.java
  src/main/java/com/prography/minari/question/service/QuestionService.java
Labels: 📃 Docs

#37 [FEAT(#22)] 인증 메일 전송 기능
  .gitignore
  build.gradle
  src/main/java/com/prography/minari/MinariApplication.java
  src/main/java/com/prography/minari/common/config/AsyncConfig.java
  src/main/java/com/prography/minari/common/execption/ErrorCode.java
  src/main/java/com/prography/minari/common/handler/GlobalExceptionHandler.java
  src/main/java/com/prography/minari/common/response/ApiResponse.java
  src/main/java/com/prography/minari/mail/dto/MailRequest.java
  src/main/java/com/prography/minari/mail/dto/MailVerificationReqDto.java
  src/main/java/com/prography/minari/mail/service/MailService.java
  src/main/java/com/prography/minari/mail/service/impl/GoogleMailClient.java
  src/main/java/com/prography/minari/user/controller/UserController.java
  src/main/resources/templates/auth-mail.html
Labels: ⚙ Setting, 📬 API, ✨ Feature, 🔨 Refactor
