Repository prography/10th-3team-minari-BE, pull requests merged in 2025-08, with the labels that each got.

#165 [REFACTOR(#149)] 미나리 달성률 -> 연속 N일차 달성 값으로 변경
  src/main/java/com/prography/minari/answer/service/AnswerService.java
  src/main/java/com/prography/minari/common/util/AnalyticsUtil.java
  src/test/java/com/prography/minari/common/util/AnalyticsUtilTest.java
Labels: 🔨 Refactor

#164 [REFACTOR(#148)] 이메일 인증 코드 저장소를 PostgreSQL → Redis로 변경
  src/main/java/com/prography/minari/common/service/impl/RedisProcessor.java
  src/main/java/com/prography/minari/mail/service/MailService.java
  src/main/java/com/prography/minari/user/service/UserService.java
Labels: ✨ Feature, 🔨 Refactor

#169 [Feat(#168)] pg요청을 위해 사용자 id를 64길이의 문자열로 변환하는 util 개발
  src/main/java/com/prography/minari/answer/repository/AnswerRepository.java
  src/main/java/com/prography/minari/common/util/uuid/UuidCreateUtil.java
  src/main/java/com/prography/minari/user/dto/UserFindResDto.java
  src/main/java/com/prography/minari/user/service/UserService.java
  src/test/java/com/prography/minari/common/util/uuid/UuidCreateUtilTest.java
Labels: ✨ Feature
